# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-05 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_auto_20190203_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email_id', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=150)),
                ('choose_activity', models.CharField(choices=[('women development', 'WOMEN DEVELOPMENT'), ('awareness session', 'AWARENESS SESSION'), ('medical camp', 'MEDICAL CAMP'), ('vocational training', 'VOCATION TRAINING')], max_length=4)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
