# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-05 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='choose_activity',
            field=models.CharField(choices=[('W', 'WOMEN DEVELOPMENT'), ('A', 'AWARENESS SESSION'), ('M', 'MEDICAL CAMP'), ('V', 'VOCATION TRAINING')], max_length=4),
        ),
    ]
