# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-28 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrbanDevelopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('target_areas', models.CharField(max_length=150)),
                ('problems', models.CharField(max_length=200)),
                ('activities', models.TextField()),
            ],
        ),
    ]
