# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-28 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_urbandevelopment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urbandevelopment',
            name='problems',
            field=models.TextField(),
        ),
    ]
