# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-28 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20190129_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='urbandevelopment',
            name='objectives',
            field=models.CharField(default=False, max_length=1000),
        ),
    ]
