# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-28 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_urbandevelopment_objectives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urbandevelopment',
            name='objectives',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
