# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-30 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_awarenesssession_medicalcamp_vocationaltraining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awarenesssession',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='medicalcamp',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='vocationaltraining',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
    ]
