# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-01 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_auto_20190131_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='urbandevelopment',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='womendevelopment',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
    ]
