# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-31 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20190131_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('embed_code', models.TextField()),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
