# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-29 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='image',
            field=models.ImageField(blank=True, upload_to='about'),
        ),
    ]
